services:
  web:
    build: frontend/
    ports:
      - "8080:80"

  auth:
    build: auth/
    ports:
      - "${AUTH_PORT}:5000"
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    environment:
      - DB_HOST=mariadb
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
    
  mariadb:
    image: mariadb
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWD}
